AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  SenderEmail:
    Type: String
    Description: "Sender email address"
  ReceiverEmail:
    Type: String
    Description: "Receiver email address"
  AppPassword:
    Type: String
    Description: "App password for email"

Resources:
  ContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref AWS::StackName
      CodeUri: ./
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 30
      LoggingConfig:
        LogGroup: !Ref ContactFormLogGroup
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - POST
          AllowHeaders:
            - Content-Type
      Environment:
        Variables:
          SENDER_EMAIL: !Ref SenderEmail
          RECEIVER_EMAIL: !Ref ReceiverEmail
          APP_PASSWORD: !Ref AppPassword

  ContactFormLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AWS::StackName}"
      RetentionInDays: 30

Outputs:
  ContactFormUrl:
    Description: "Contact Form API URL"
    Value: !GetAtt ContactFormFunctionUrl.FunctionUrl
